### ISSUE TITLE
value should be a JSON object

### ISSUE THREAD

**Issue by kubex75** [cuimingkun/zbx_tem_redis#1]
Hi,

Your template looks very good and it is promising, but i have some problem. After setting ale requirements i have warnig on zabbix:
"value should be a JSON object"

If i manualy check Redis Discovery for Port on host with agent then command return redis port in JSON format. This is very strange. Do you know what could be the cause of this issue?

Thanks in advance 
Jakub

**Comment by cuimingkun** [comment]
Please check the return format of the following key command.
redis.port.discovery
redis.repl.discovery
redis.config.json[xxxx]
redis.info.json[xxxx]

**Comment by kubex75** [comment]
Thank you very much for fast respone. 
After i sned redis.port.discovery from zabbix server to client i have receive null return.
After some investigation i found that selinux is the problem on RedHat ;)

Need to bypass this, but i think everything will work OK.
