### ISSUE TITLE
can not get redis.port.discovery 

### ISSUE THREAD

**Issue by doudou0312** [cuimingkun/zbx_tem_redis#2]
hello,I found something wrong with userparameter_redis_lld_plus.conf. my zabbix version is 3.4.7.
I am changed the /etc/sudoers ,add zabbix ALL=NOPASSWD: ALL 
then modify userparameter_redis_lld_plus.conf like underline
UserParameter=redis.port.discovery,**sudo** ss -4lp|grep redis-server|awk -F':' '{print $2}'|awk '{print $1}'|grep -v 16379| awk NF | sed -e s/^/'{"{#REDIS_PORT}": "'/g -e s/'$'/'"},'/g | tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}'\n'/g
...
UserParameter=redis.repl.discovery,**sudo** ss -4lp|grep redis-server|awk -F':' '{print $2}'|awk '{print $1}'| awk NF|while read line; do role=`(echo info ; sleep 0.1)|telnet 127.0.0.1 $line 2>/dev/null|grep 'role:slave'|awk -F ':' '{print $2}'`;if [ "$role" == "slave" ] ;then echo "SLAVE:$line"|sed -e s/^/'{"{#REDIS_PORT_'/g -e s/'$'/'"},'/g -e s/':'/'}": "'/g ; fi;done| tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}/g

**Comment by cuimingkun** [comment]
When using "tr -d \n", Need transfer "\n".
Try to modified to "tr -d \\n"

**Comment by kpod13** [comment]
@doudou0312 you also could use suid bit on ss.

**Comment by OrangeDog** [comment]
The port is in process name, so you can find them without root access like this
```
for pid in $(pgrep redis-server); do ps -p $pid -o command=; done | sed -r 's/.*:([0-9]+).*/\1/'
```

**Comment by cuimingkun** [comment]
@OrangeDog 
Good advice,It's safer. It was also used in the first place.
But, it does not apply to 2.6 and previous versions.
