### ISSUE TITLE
Item Preprocessing failures

### ISSUE THREAD

**Issue by ang3lwitch** [cuimingkun/zbx_tem_redis#3]
I am getting tons of prprocessing step failures that I am not understanding how to resolve.

![image](https://user-images.githubusercontent.com/24722902/44535944-55a03480-a6c9-11e8-879c-de783e63fa39.png)

If i run the basic command from the userparameter_redis_lld.conf, i do get something as a test.

`ss -4lp|grep redis-server|awk -F':' '{print $2}'|awk '{print $1}'| awk NF|while read line; do role=`(echo info ; sleep 0.1)|telnet 192.168.63.61 $line 2>/dev/null|grep 'role:slave'|awk -F ':' '{print $2}'`;if [ "$role" == "slave" ] ;then echo "SLAVE:$line"|sed -e s/^/'{"{#REDIS_PORT_'/g -e s/'$'/'"},'/g -e s/':'/'}": "'/g ; fi;done| tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}/g`

#result below
{"data":[{"{#REDIS_PORT_SLAVE}": "vcom-tunnel"}]}

**Comment by cuimingkun** [comment]
You need to split the command into execution.Troubleshooting problems.

**Comment by ang3lwitch** [comment]
Well, I am not entirely sure what I did other than
re-apply userparameter file and template again

It works! yay!

Thanks, i really enjoy easy userparameter files and templates.
