### ISSUE TITLE
Does not work with authorization

### ISSUE THREAD

**Issue by darksmoke** [cuimingkun/zbx_tem_redis#4]
1. Does not work with authorization. Redoing a lot and lost the possibility of autodiscoding.
2. IP must be transferred to Zabbix {HOST.IP <1-9>}

`UserParameter=redis.port.discovery,ss -4lp|grep redis-server|awk -F':' '{print $2}'|awk '{print $1}'| awk NF | sed -e s/^/'{"{#REDIS_PORT}": "'/g -e s/'$'/'"},'/g | tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}/g
UserParameter=redis.port.ping[*],(echo AUTH PASS; echo ping ;sleep 0.1) |telnet 10.1.110.77 $1 2>/dev/null |grep 'PONG'|wc -l
UserParameter=redis.info.json[*],(echo AUTH PASS; echo info ; sleep 0.1)| telnet 10.1.110.77 $1 2>/dev/null | grep ':'| grep -v ^# | grep -v ^db | awk NF | sed -e s/:ok$/:yes/g -e s/^/'"'/g -e s/'$'/'",'/g -e s/':'/'":"'/g | tr -d \\n | sed -e s/^/'{"redis_info":{'/g -e s/',$'/}}/g
UserParameter=redis.config.json[*],(echo AUTH PASS; echo "config get *" ; sleep 0.1)| redis-cli -h 10.1.110.77 -p $1 -a PASS |awk '{print $NF}'|sed -e 's/^/"&/g' -e 's/$/&"/g' |sed 'N;s/\n/:/g' |sed -e s/'$'/','/g| tr -d \\n | sed -e s/^/'{"redis_config":{'/g -e s/',$'/}}/g
#discovery slave
UserParameter=redis.repl.discovery,ss -4lp|grep redis-server|awk -F':' '{print $2}'|awk '{print $1}'| awk NF|while read line; do role=`(echo info ; sleep 0.1)|telnet 10.1.110.77 $line 2>/dev/null|grep 'role:slave'|awk -F ':' '{print $2}'`;if [ "$role" == "slave" ] ;then echo "SLAVE:$line"|sed -e s/^/'{"{#REDIS_PORT_'/g -e s/'$'/'"},'/g -e s/':'/'}": "'/g ; fi;done| tr -d \\n | sed -e s/^/'{"data":['/g -e s/',$'/]}/g
UserParameter=redis.slaveinfo.json[*],(echo AUTH PASS; echo info Replication; sleep 0.1)| telnet 10.1.110.77 $1 2>/dev/null | grep ':'| grep -v ^# | grep -v ^db | awk NF | sed -e s/:ok$/:yes/g -e s/^/'"'/g -e s/'$'/'",'/g -e s/':'/'":"'/g | tr -d \\n | sed -e s/^/'{"redis_slaveinfo":{'/g -e s/',$'/}}/g`

**Comment by OrangeDog** [comment]
The password should really be a parameter. Also please format this properly in a code block.
