### ISSUE TITLE
Wrong template version

### ISSUE THREAD

**Issue by sgnsys3** [cuimingkun/zbx_tem_redis#8]
I see in the lastest commit. The template file version is 4.2. Is it normal?

**Comment by bpress** [comment]
This template is not compatible with version 3.4. Not only because of the template version tag, but also for additional unsupported tags in 3.4, such as `<tag>` and `<timeout>.`

Either rework it for 3.4 or change requirements.

**Comment by altmas5** [comment]
Hi @sgnsys3 
Try with an oldest commit:
https://github.com/cuimingkun/zbx_tem_redis/tree/fca4e7a302e60b02948f6da25a3865e0aa2d0463

**Comment by sgnsys3** [comment]
@altmas5  I have work around by download old commit and It works! Thanks for comment

**Comment by altmas5** [comment]
You're welcome @sgnsys3

**Comment by cuimingkun** [comment]
Since the merged template version is 4.2 and some tags have been added.
Now it's revised to be based on version 3.4.
Low version templates can be used on high versions,But,higher version templates cannot be used for lower versions.
